development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: api_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: api_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: etsndidn
  username: etsndidn
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  host: babar.elephantsql.com
