"""change_players_to_ids_on_games

Revision ID: 2852e76673dd
Revises: 292176282743
Create Date: 2015-02-10 12:46:28.069172

"""

# revision identifiers, used by Alembic.
revision = '2852e76673dd'
down_revision = '292176282743'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('team1defense_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('team1offense_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('team2defense_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('team2offense_id', sa.Integer(), nullable=True))

    op.create_foreign_key(None, 'games', 'players', ['team1offense_id'], ['id'])
    op.create_foreign_key(None, 'games', 'players', ['team2offense_id'], ['id'])
    op.create_foreign_key(None, 'games', 'players', ['team1defense_id'], ['id'])
    op.create_foreign_key(None, 'games', 'players', ['team2defense_id'], ['id'])

    op.drop_column('games', 'team1defense')
    op.drop_column('games', 'team2defense')
    op.drop_column('games', 'team1offense')
    op.drop_column('games', 'team2offense')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('team2offense', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('team1offense', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('team2defense', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('team1defense', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')

    op.drop_column('games', 'team2offense_id')
    op.drop_column('games', 'team2defense_id')
    op.drop_column('games', 'team1offense_id')
    op.drop_column('games', 'team1defense_id')
    ### end Alembic commands ###
