source "https://rubygems.org"

gem "active_model_serializers"
gem "rails", "4.2.1"
gem "pg"
gem "pry-rails"
gem "rack-cors", require: "rack/cors"
gem "thin"

group :development, :test do
  gem "rspec-rails"
end

group :production do
  gem "rails_12factor"
end
